# Site wide configuration

title: Jin Shang
locale: en_US
description: from Harbin, China
logo: weblogo.jpg
search: true
# url: http://www.cs.cmu.edu/~malin199
url: //js8544.github.io
# url: http://localhost:4000 

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter:  rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Jin Shang
  avatar: weblogo.jpg
  email: shangjin1997@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: js8544
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: jin-shang-49609710a
  instagram: js8544
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: 
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
