# Site wide configuration

title: Zhuoqun Li
locale: en_US
description: Zhuoqun Li's personal website
logo: weblogo.png
search: true
url: https://zli218.github.io

# Jekyll configuration

permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

mathjax: true

include: [".htaccess"]
exclude:
  [
    "lib",
    "config.rb",
    "Capfile",
    "config",
    "log",
    "Rakefile",
    "Rakefile.rb",
    "tmp",
    "less",
    "*.sublime-project",
    "*.sublime-workspace",
    "test",
    "spec",
    "Gruntfile.js",
    "package.json",
    "node_modules",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "vendor",
  ]

# Site owner
owner:
  name: Zhuoqun Li
  avatar: weblogo.png
  email: zli82@lsu.edu
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: https://github.com/zli218
  stackexchange: #username
  linkedin: https://www.linkedin.com/in/zhuoqun-li-bb02a1298/
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
