# Site wide configuration

#title: Lin Ma - Carnegie Mellon University
title: Lin Ma
locale: en_US
#description: Describe your website here.
logo: weblogo.png
search: true
url: http://www.cs.cmu.edu/~malin199

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Lin Ma 
  avatar: bio-photo.jpg
  email: lin.ma@cs.cmu.edu
  disqus-shortname:
  twitter: #username
  facebook: lin.ma.39794
  github: malin1993ml
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: LinMa1
    analytics: malin1993ml
    verify:
    ad-client:
    ad-slot:
  bing-verify:
